import { readFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { discoverProject } from './discover.mjs';
import { loadTestgenConfig, validateTestgenConfig } from './config.mjs';
import { buildTestPlan } from './test-plan.mjs';
import { exists, stableStringify, writeDeterministic } from './utils.mjs';

function importLine(runner) {
  return runner === 'jest'
    ? "import { describe, expect, test } from '@jest/globals';"
    : "import { describe, expect, test } from 'vitest';";
}

function generatedContractTest(manifest, config) {
  const snapshot = stableStringify({
    contentTypes: manifest.contentTypes,
    components: manifest.components,
    routes: manifest.routes,
    pii: config.pii?.fields ?? [],
  }, 2).trim();
  return `// Generated by strapi-agent-squad. Do not edit; change .agents/testgen.config.yaml or source schemas.\n${importLine(config.runner)}\nimport { duplicateRoutes, missingComponentReferences, missingRelationTargets, schemaContractViolations, unsafePrivateFields } from 'strapi-agent-squad/testkit';\n\nconst snapshot = ${snapshot};\n\ndescribe('generated Strapi contracts', () => {\n  test('route method/path/scope combinations are unique', () => {\n    expect(duplicateRoutes(snapshot.routes)).toEqual([]);\n  });\n\n  test('component references resolve', () => {\n    expect(missingComponentReferences(snapshot.contentTypes, snapshot.components)).toEqual([]);\n  });\n\n  test('application relation targets resolve', () => {\n    expect(missingRelationTargets(snapshot.contentTypes)).toEqual([]);\n  });\n\n  test('schema invariants are internally consistent', () => {\n    expect(schemaContractViolations(snapshot.contentTypes)).toEqual([]);\n  });\n\n  test('declared PII fields exist and are private', () => {\n    expect(unsafePrivateFields(snapshot.contentTypes, snapshot.pii)).toEqual([]);\n  });\n});\n`;
}

function generatedRouteTest(manifest, config) {
  const routes = manifest.routes.map((route) => ({
    method: route.method,
    path: route.path,
    handler: route.handler,
    scope: route.scope,
    auth: route.auth,
    policies: route.policies,
  }));
  const allowlist = (config.publicRoutes ?? []).map((route) => `${String(route.method).toUpperCase()} ${route.path}`);
  return `// Generated by strapi-agent-squad. Do not edit.\n${importLine(config.runner)}\n\nconst routes = ${stableStringify(routes, 2).trim()};\nconst publicAllowlist = new Set(${JSON.stringify(allowlist)});\n\ndescribe('generated Strapi route security', () => {\n  test('all routes have static handlers', () => {\n    expect(routes.filter((route) => !route.handler || typeof route.handler !== 'string')).toEqual([]);\n  });\n\n  test('anonymous routes are explicitly approved', () => {\n    const unexpected = routes\n      .filter((route) => route.auth === false)\n      .map((route) => \`${'${route.method} ${route.path}'}\`)\n      .filter((route) => !publicAllowlist.has(route));\n    expect(unexpected).toEqual([]);\n  });\n\n  test('admin routes never disable authentication', () => {\n    expect(routes.filter((route) => route.scope === 'admin' && route.auth === false)).toEqual([]);\n  });\n});\n`;
}

function generatedSchemaCases(manifest, config, testPlan) {
  const snapshot = stableStringify({ contentTypes: manifest.contentTypes, testPlan }, 2).trim();
  return `// Generated by strapi-agent-squad. Do not edit.\n${importLine(config.runner)}\nimport { plannedSchemaViolations } from 'strapi-agent-squad/testkit';\n\nconst snapshot = ${snapshot};\n\ndescribe('generated Strapi schema cases', () => {\n  test('all generated static schema cases remain backed by their schema contracts', () => {\n    expect(plannedSchemaViolations(snapshot.contentTypes, snapshot.testPlan.tests)).toEqual([]);\n  });\n});\n`;
}

function generatedRuntimeTest(config) {
  const expectations = stableStringify(config.routeExpectations ?? [], 2).trim();
  return `// Generated by strapi-agent-squad. Do not edit. Runtime is opt-in and loopback-only.\n${importLine(config.runner)}\nimport { assertLoopbackUrl, createIsolatedFetch } from 'strapi-agent-squad/testkit';\n\nconst baseUrl = assertLoopbackUrl(${JSON.stringify(config.runtime.baseUrl)});\nconst isolatedFetch = createIsolatedFetch(fetch);\nconst cases = ${expectations};\n\ndescribe('generated isolated Strapi runtime contracts', () => {\n  for (const item of cases) {\n    test(item.id, async () => {\n      const url = new URL(item.path, baseUrl);\n      const response = await isolatedFetch(url, {\n        method: item.method,\n        headers: item.headers,\n        body: item.body === undefined ? undefined : JSON.stringify(item.body),\n        redirect: 'manual',\n        signal: AbortSignal.timeout(5000),\n      });\n      expect(item.expectedStatus).toContain(response.status);\n      const text = await response.text();\n      expect(text).not.toMatch(/(?:stack|authorization|password|secret|token)[\\s\\S]{0,40}(?:at |bearer |[:=])/i);\n    });\n  }\n});\n`;
}

function generatedFiles(manifest, config, testPlan) {
  const files = new Map([
    ['tests/generated/strapi-contracts.generated.test.ts', generatedContractTest(manifest, config)],
    ['tests/generated/strapi-routes.generated.test.ts', generatedRouteTest(manifest, config)],
    ['tests/generated/strapi-schema-cases.generated.test.ts', generatedSchemaCases(manifest, config, testPlan)],
    ['.agents/generated/strapi-test-manifest.json', stableStringify({ ...manifest, testPlan })],
  ]);
  if (config.runtime?.enabled) files.set('tests/generated/strapi-runtime.generated.test.ts', generatedRuntimeTest(config));
  return files;
}

export async function generateTests(projectRoot, { write = false } = {}) {
  const root = path.resolve(projectRoot);
  const manifest = await discoverProject(root);
  const config = await loadTestgenConfig(root);
  const validation = validateTestgenConfig(manifest, config);
  if (validation.blockers.length > 0) {
    const error = new Error(`Test generation blocked by ${validation.blockers.length} unresolved contract decision(s)`);
    error.exitCode = 2;
    error.validation = validation;
    throw error;
  }

  const testPlan = buildTestPlan(manifest, config);
  const files = generatedFiles(manifest, config, testPlan);
  const changes = [];
  for (const [relative, content] of files) {
    const absolute = path.join(root, relative);
    const current = (await exists(absolute)) ? await readFile(absolute, 'utf8') : null;
    if (current !== content) changes.push(relative);
    if (write) await writeDeterministic(absolute, content);
  }
  const runtimeFile = path.join(root, 'tests/generated/strapi-runtime.generated.test.ts');
  if (!files.has('tests/generated/strapi-runtime.generated.test.ts') && await exists(runtimeFile)) {
    changes.push('tests/generated/strapi-runtime.generated.test.ts');
    if (write) await rm(runtimeFile);
  }
  return { manifest, config, testPlan, validation, changes, files: [...files.keys()] };
}

export async function checkGeneratedTests(projectRoot) {
  const result = await generateTests(projectRoot, { write: false });
  if (result.changes.length > 0) {
    const error = new Error(`Generated tests are stale or missing: ${result.changes.join(', ')}`);
    error.exitCode = 1;
    error.changes = result.changes;
    throw error;
  }
  return result;
}

export async function cleanGeneratedTests(projectRoot) {
  await rm(path.join(projectRoot, 'tests', 'generated'), { recursive: true, force: true });
  await rm(path.join(projectRoot, '.agents', 'generated'), { recursive: true, force: true });
}
